version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - DATABASE_URL=file:/app/prisma/test.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=test-secret-for-local-testing-only
      - NGINX_ENDPOINT=http://minio:9000
      - NGINX_EXTERNAL_URL=http://localhost:9000
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - BANDWIDTH_FREE_TOTAL=50
      - BANDWIDTH_PREMIUM_TOTAL=250
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DAILY_DOWNLOAD_LIMIT=10
    volumes:
      - ./prisma:/app/prisma
    depends_on:
      - redis
      - minio
    networks:
      - test-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - test-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - test-network

  # Test runner - runs tests against the webapp
  test-runner:
    image: curlimages/curl:latest
    depends_on:
      - webapp
    volumes:
      - ./test-api.sh:/test-api.sh:ro
    entrypoint: ["/bin/sh"]
    command: ["-c", "sleep 10 && sh /test-api.sh"]
    environment:
      - BASE_URL=http://webapp:3000
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  minio-data: